services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    container_name: backend
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/shoptech
    networks:
      - network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shoptech
  
  pdadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres_data: