shoptech_dbt:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME', 'shoptech') }}"
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      pass: "{{ env_var('DB_PASS', 'qwerty1234') }}"
      schema: "{{ env_var('DB_SCHEMA', 'public') }}"
      port: "{{ env_var('DB_PORT', '5432') | int }}"
      threads: "{{ env_var('DB_THREADS', '1') | int }}"
      type: "{{ env_var('DB_TYPE', 'postgres') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
  target: dev