name: Backend Continous Integration
  
on: push

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install
        working-directory: backend

      - name: Run Code Linter
        run: poetry run task lint
        working-directory: backend

      - name: Run Pytest
        run: poetry run task test
        working-directory: backend